### ISSUE TITLE
SIGSEGV JVM crash

### ISSUE THREAD

**Issue by dharmeshgordhan** [corretto/corretto-17#178]
Thank you for taking the time to help improve OpenJDK and Corretto.

If your request concerns a security vulnerability then please report it by email to aws-security@amazon.com instead of here. (You can find more information regarding security issues at https://aws.amazon.com/security/vulnerability-reporting/.)

Otherwise, if your issue concerns OpenJDK and is not specific to Corretto we ask that you raise it to the OpenJDK community. Depending on your contributor status for OpenJDK, please use the [JDK bug system](https://bugs.openjdk.java.net/) or the appropriate [mailing list](http://mail.openjdk.java.net/mailman/listinfo) for the given problem area or [update project](http://mail.openjdk.java.net/mailman/listinfo/jdk-updates-dev).

If your issue is specific to Corretto, then you are in the right place. Please proceed with the following.

### Describe the bug
Not sure if this is specific to Corretto. Thought I would ask here for advice on how to gather more information, and figure out the right place to raise this. 

A Java app we run, Confluence, failed. It output a [hs_err_pid.log](https://github.com/corretto/corretto-17/files/14382478/hs_err_pid.log) (attached). The hs_err_*.log file indicates `SIGSEGV`. The Confluence support team have attributed this issue to Corretto.

### To Reproduce
Unsure at the moment. Hoping by understanding the hs_err_*.log we can better understand how to reproduce it. 

### Expected behavior
Not crash.

### Platform information
    OS: Amazon Linux 2
    Version: OpenJDK Runtime Environment Corretto-17.0.10.8.1 (17.0.10+8) (build 17.0.10+8-LTS)

[hs_err_pid.log](https://github.com/corretto/corretto-17/files/14382478/hs_err_pid.log)

**Comment by alvdavi** [comment]
Hi,
I've been taking a look to the hs_err_pid.log file, and there is interesting information in there. The log is for a segmentation fault in libjvm.so, which suggest something went wrong on the JVM code. But as we dig deeper, we start to see unusual information.
The first thing worth mentioning is that there are is extremely high amount of repeated frames on the thread that triggerred the exception:
```
J 101210 c2 com.google.template.soy.data.SoyAbstractMap.coerceToString()Ljava/lang/String; (113 bytes) @ 0x00007f8baa58ce7c [0x00007f8baa58afa0+0x0000000000001edc]
J 101210 c2 com.google.template.soy.data.SoyAbstractMap.coerceToString()Ljava/lang/String; (113 bytes) @ 0x00007f8baa58ce7c [0x00007f8baa58afa0+0x0000000000001edc]
J 101210 c2 com.google.template.soy.data.SoyAbstractMap.coerceToString()Ljava/lang/String; (113 bytes) @ 0x00007f8baa58ce7c [0x00007f8baa58afa0+0x0000000000001edc]
```
I haven't counted them, but everything here seems to indicate that thread entered an infinite recursion loop in the SoyAbstractMap class. However, this should have reported a StackOverflowError, instead of having a segmentation fault on libjvm. But reporting a StackOverflowError takes some amount of work, and if the stack is completely full, we can't really perform any work. For this reason, there is a small difference between when the JVM considers a stack to overflow and when it actually overflows (causing a segmentation fault). The JVM reserves a few stack frames so it can take control and actually report the StackOverflowError to the user. But this time, it didn't. Why?

Here is when looking at the top of the stacktrace of the thread that triggered the exception is useful:
```
V  [libjvm.so+0x297d21]  AccessInternal::PostRuntimeDispatch<G1BarrierSet::AccessBarrier<548964ul, G1BarrierSet>, (AccessInternal::BarrierType)2, 548964ul>::oop_access_barrier(void*)+0x1
C  [liboneagentjava.so+0x2a3df4]
C  [liboneagentjava.so+0x2a58c4]
C  [liboneagentjava.so+0x2a5bd1]
C  [liboneagentjava.so+0x37a8c7]
C  [liboneagentjava.so+0x37aa67]
C  [liboneagentjava.so+0x2aafe5]
C  [liboneagentjava.so+0x2b7190]
C  [liboneagentjava.so+0x2b7ff1]
V  [libjvm.so+0xa029ab]  JvmtiExport::post_class_prepare(JavaThread*, Klass*)+0x15b
V  [libjvm.so+0x805847]  InstanceKlass::link_class_impl(JavaThread*)+0x4b7
V  [libjvm.so+0x80650f]  InstanceKlass::initialize_impl(JavaThread*)+0x10f
V  [libjvm.so+0x820ceb]  InterpreterRuntime::_new(JavaThread*, ConstantPool*, int)+0x15b
j  com.atlassian.soy.impl.data.AccessorSoyValueProvider.doResolve()Lcom/google/template/soy/data/SoyValue;+20
J 101210 c2 com.google.template.soy.data.SoyAbstractMap.coerceToString()Ljava/lang/String; (113 bytes) @ 0x00007f8baa58d124 [0x00007f8baa58afa0+0x0000000000002184]
J 101210 c2 com.google.template.soy.data.SoyAbstractMap.coerceToString()Ljava/lang/String; (113 bytes) @ 0x00007f8baa58ce7c [0x00007f8baa58afa0+0x0000000000001edc]
J 101210 c2 com.google.template.soy.data.SoyAbstractMap.coerceToString()Ljava/lang/String; (113 bytes) @ 0x00007f8baa58ce7c [0x00007f8baa58afa0+0x0000000000001edc]
```

In that part of the stacktrace we can see how the JVM took control, and we see some frames that correspond to VM code. However, eventually control moves from libjvm.so to liboneagentjava.so. This is not part of the JVM. It seems that this agent is trying to do something when a JVM error happens, and although control eventually goes back to the JVM, this is already too late. Those few extra spare frames are already gone, and a segmentation fault is the only option here.

That agent is loaded as part of the JVM startup, and we can see this in the JVM parameters:
```
-agentpath:/opt/dynatrace/oneagent/agent/bin/1.283.132.20240205-143805/linux-x86-64/liboneagentloader.so=loglevelcon=none,datastorage=/var/lib/dynatrace/oneagent/datastorage,logdir=/var/log/dynatrace/oneagent
```

There are other clues in the file, but they all point to this. For example, we can see how StackOverflowErrors are being thrown:
```
Event: 1533.504 Thread 0x00007f8beeeeb590 Exception <a 'java/lang/StackOverflowError'{0x000000079ed34688}> (0x000000079ed34688) 
thrown [src/hotspot/share/runtime/javaCalls.cpp, line 400]
Event: 1533.504 Thread 0x00007f8beeeeb590 Exception <a 'java/lang/StackOverflowError'{0x000000079ed39c40}> (0x000000079ed39c40) 
thrown [src/hotspot/share/runtime/javaCalls.cpp, line 400]
```

We can also see how the actual `java.lang.Error` class has been redefined, most likely by the agent inserting code to take control whenever one of these are generate as we saw in the stack trace:
```
Classes redefined (19 events):
...
Event: 311.679 Thread 0x00007f8beca8e3f0 redefined class name=java.lang.Throwable, count=1
Event: 311.679 Thread 0x00007f8beca8e3f0 redefined class name=java.lang.Error, count=2
...
```

So, to summarize:
- This is not a JVM error
- It seems the issue originates as a StackOverflow on `com.google.template.soy.data.SoyAbstractMap.coerceToString()`
- An agent installed on startup hijacks the regular StackOverflowError being thrown and causes the stack to overflow for real, causing a Segmentation Fault and hiding the original problem.

**Comment by dharmeshgordhan** [comment]
Thank you very much. I really appreciate you taking the time to walk through the hs_err_pid.log file and what it means. Since this isn't a JVM error, I'll take this away and see how we might discover and solve the original problem.
