### ISSUE TITLE
Why 'Stream.toList()' call 'new ArrayList()' twice?

### ISSUE THREAD

**Issue by PgmJun** [corretto/corretto-17#179]
SSIA.

I can't understand this architecture.
plz explain reason for me..🥲

### Stream.toList()
```java
default List<T> toList() {
        return (List<T>) Collections.unmodifiableList(new ArrayList<>(Arrays.asList(this.toArray())));
    }
```

### Arrays.asList()
```java
public static <T> List<T> asList(T... a) {
        return new ArrayList<>(a);
    }
```

**Comment by caojoshua** [comment]
Adding the sources for reference
[Stream::toList()](https://github.com/corretto/corretto-17/blob/9b3f17a492801bed685300b308e258f58b70f24e/src/java.base/share/classes/java/util/stream/Stream.java#L1198)
[Arrays::asList()](https://github.com/corretto/corretto-17/blob/9b3f17a492801bed685300b308e258f58b70f24e/src/java.base/share/classes/java/util/Arrays.java#L4122)

I'm not sure. Seems like the `new ArrayList` in `Stream::toList` is unnecessary.

The only argument I could think of is that `Arrays::asList()` returns a `List`, and is not guaranteed to return an `ArrayList`. Maybe `Stream::toList` specifically wants that list to be an ArrayList, but I cannot think of a good reason why.

This code is [in the @implSpec](https://github.com/corretto/corretto-17/blob/9b3f17a492801bed685300b308e258f58b70f24e/src/java.base/share/classes/java/util/stream/Stream.java#L1186), but I suspect this can be changed as well.

@PgmJun my answer is that is probably an oversight and should not be there. I can test removing the redundant `new ArrayList()`. But if you would like you can [contribute the change yourself](https://openjdk.org/contribute/).

**Comment by PgmJun** [comment]
@caojoshua 

Thank you! I'll test it myself and if there's no problem, I'll contribute!

**Comment by mrserb** [comment]
Note that this are two different classes with the same name.

**Comment by alvdavi** [comment]
To expand on Sergey's answer, there are two classes here, `java.util.ArrayList<T>` and `java.util.Arrays.ArrayList<T>`, which can lead to the confusion. The second one is a `private static` class.

There is a reason why the `toList` method is implemented that way. Our intention is to have an unmodifiable list, but wrapping an instance of `java.util.Arrays.ArrayList<T>` is not enough guarantee, because the [constructor](https://github.com/corretto/corretto-17/blob/9b3f17a492801bed685300b308e258f58b70f24e/src/java.base/share/classes/java/util/Arrays.java#L4136) for it picks the array passed to it (which could then still be accessed). By adding the extra call to `new ArrayList<>(...)` in `Stream.toList` we ensure a defensive copy of the array is done by the `java.util.ArrayList` [constructor](https://github.com/corretto/corretto-17/blob/9b3f17a492801bed685300b308e258f58b70f24e/src/java.base/share/classes/java/util/ArrayList.java#L186).

For that reason, the PR can't be merged. But even if this change made sense, it would be a change that would be better implemented on the OpenJDK source code upstream and not directly into Corretto.

**Comment by PgmJun** [comment]
@alvdavi 

Oh it was a different class. I got it. Thank you for your answer
