### ISSUE TITLE
Offer cryptographic signatures of downloadable artefacts

### ISSUE THREAD

**Issue by mkesper** [corretto/corretto-17#29]
If your issue is specific to Corretto, then you are in the right place. Please proceed with the following.

### Describe the bug
Most Amazon Corretto 17 Downloads from Github can only be verifyed by MD5, cryptographic signature files (*.sig) are only available for some downloads.

### To Reproduce
Visit https://github.com/corretto/corretto-17/releases

### Expected behavior
For every binary artefact there exists at least a downloadable and easily verifyable cryptographically valid checksum. Better even a signature file that can be verified by a published cryptographical key.
![corretto_release](https://user-images.githubusercontent.com/3063558/144077899-9a977730-8495-42ef-b85d-a5e0a7df08c0.png)

**Comment by mkesper** [comment]
I'm astonished there is no reaction at all after 3 days. :-1:

**Comment by alvdavi** [comment]
Hi, Michael,

I'm deeply sorry for the delay in answering.

Every artifact we publish it is signed and can be verified to come from us. We only offer the `sig` files for `tar.gz` or `zip` files that do not support signatures directly embedded into the file.

For Linux, our `rpm` and `deb` files are signed with the same cryptographic GPG key we use to provide the `sig` files. This key is also used to validate our yum/apt repositories.

For windows artifacts distributed as `msi`, those are signed using Microsoft Authenticode. These are not signed using the same GPG key, but signed with a trusted certificate that Windows will recognize. This is the signature that appears in the "Digital Signatures" tab of the file properties. Additionally, all windows binaries (`exe` and `dll` files) are also signed using the same certificate. This is true even when downloading windows binaries in a `zip` file instead of the `msi` file.

macOS follows a very similar pattern as Windows, although in this case, using Apple signing technology and a different certificate, one trusted by mac systems. The `pkg` file includes an embedded signature and so do all the binaries (executables and `dylib` libraries) provided with the package.

Both Windows and macOS signatures are automatically verified during installation and when executing, however, this process is transparent as long as the signature matches and is properly trusted.

**Comment by mkesper** [comment]
Thanks for the answer, valid point!

**Comment by mkesper** [comment]
The usage of md5sum still surprises me, but as a pure download checksum it might be ok.

**Comment by benty-amzn** [comment]
We definitely understand the concerns about md5. Providing alternative checksum hashes (most likely sha256) is something that has been requested before ([corretto-11 #125](https://github.com/corretto/corretto-11/issues/125)), and we do plan to offer them for a future release but can't provide a timeline at this time.

**Comment by mkesper** [comment]
As this has been handled now, I close this issue. Thanks for taking care!
