### ISSUE TITLE
Corretto Downloads

### ISSUE THREAD

**Issue by Fleshgrinder** [corretto/corretto-17#62]
I don‘t know which repository is the right one to report this issue. I chose this one because I feel that 17 should get most attention these days, since it is the latest LTS. However, this issue doesn‘t belong here.

How does https://corretto.github.io/corretto-downloads/ come into existence? The https://corretto.github.io/ page gives a 404, and following “View on GitHub” link at the top points to https://github.com/corretto/corretto-downloads also resulting in a 404. Lastly the “CONTRIBUTING” link https://corretto.github.io/corretto-downloads/CONTRIBUTING.md#security-issue-notifications results in a download of the generic AWS contributing file, but it does not actually go to a web page (and the linked fragment).

Then there is the https://corretto.github.io/corretto-downloads/latest_links/indexmap_with_checksum.json link. Given all the previous questions one has to question if it is actually genuine. How is it generated? Can we trust the checksums? Or is it that they are easily compromised if someone is able to change what we find at https://corretto.aws/ (where all the referenced files are we can download)?

I hope it is possible to resurrect https://github.com/corretto/corretto-downloads, or create it if it never existed, and to make the process behind all of this transparent. This would greatly increase trust.

Last, but not least, if would be great to have a https://corretto.github.io/available-releases.json similar to https://api.adoptium.net/v3/info/available_releases that allows dynamic resolution of the latest versions, including designation of LTS and non-LTS releases. Something like the Adoptium API would generally be a good thing to have, but that is not easily built with GitHub pages.

**Comment by lutkerd** [comment]
Hello,
Thanks for reaching out as we were hoping to get some direct feedback when we published this. Let me try to address all of the questions here.

The webpage for https://corretto.github.io/corretto-downloads/ is a standard GitHub Page, but the underlying repository is private. We did not think external customer would need access to it and would prefer to keep it private, though there isn't anything in it other than the markdown for that page, the json. and some boilerplate. I will see what I can do about removing some of the extraneous links, using GitHub's built in themes we don't have a ton of control. I will also discuss with the team making the repo public. We are planning the `https://corretto.github.io/` page, but wanted to get the download page out since that has been a frequent ask for sometime.

The indexmap_with_checksum.json is generated by our internal release tooling and we commit the updated version when doing the release and creating GitHub release pages. It is in the separate GitHub repo that has no connection to the actual Corretto.aws pages or download infrastructure. There may be short periods of time during a release where the Corretto.aws page is getting updating and the GitHub repo has no yet been updated, or vice versa, and the do not match. Since they are disconnected we cannot make it an atomic operation.

I think we could add an additional JSON file that contains more data about the releases, what the LTS and Feature Releases are, etc. I will take this back to the team and go through some of the other requests in the issues and see what we can come up with.

**Comment by Fleshgrinder** [comment]
Thanks for the response. Making it public would be very helpful, also for reporting issues with it and asking questions like this one. That the repository is private is something that users cannot know, since it gives the standard 404 (for obvious security reasons, but it is not helping with an otherwise public thing). Having access to the code also helps with establishing trust, tremendously so even. 😊

> There may be short periods of time during a release where the Corretto.aws page is getting updating and the GitHub repo has no yet been updated, or vice versa, and the do not match. Since they are disconnected we cannot make it an atomic operation.

I don’t think that it needs to be atomic, but the JSON that this page offers should be updated after corretto.aws is updated to avoid failures of automated tools that use it.

**Comment by lutkerd** [comment]
The [corretto-downloads](https://github.com/corretto/corretto-downloads) repo is public now.

**Comment by lutkerd** [comment]
No further action at this time. We are tracking creation of the corretto.github.io page internally as well as developing the more dynamic APIs and methods for getting release info.
